export const FIELDS_OF_WORK = [
  "Legal",
  "Medical",
  "Technical",
  "Scientific",
  "Financial",
  "Business / Corporate",
  "Diplomatic / Political",
  "Government / Institutional",
  "Security / Defense",
  "Information Technology",
  "Marketing / Advertising",
  "Media / Journalism",
  "Audiovisual / Entertainment",
  "Localization",
  "Literary",
  "Academic / Education",
  "Humanitarian / NGO / Development",
  "Religious / Theological",
  "Tourism / Hospitality",
  "Agriculture",
  "Environment / Climate",
  "Transport / Logistics",
  "Energy / Oil & Gas",
  "Manufacturing / Industrial",
  "Telecommunications",
] as const
