-- Update profiles table
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS first_name TEXT,
ADD COLUMN IF NOT EXISTS last_name TEXT;

-- Update interpreters table
ALTER TABLE public.interpreters
ADD COLUMN IF NOT EXISTS birthday DATE,
ADD COLUMN IF NOT EXISTS mother_tongues TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS languages_a TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS languages_b TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS languages_c TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS sign_interpreter BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS interpreter_since INTEGER,
ADD COLUMN IF NOT EXISTS primary_expertise TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS secondary_expertise TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS aiic_member BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS other_accreditation TEXT,
ADD COLUMN IF NOT EXISTS highest_education TEXT,
ADD COLUMN IF NOT EXISTS school TEXT,
ADD COLUMN IF NOT EXISTS graduation_date DATE,
ADD COLUMN IF NOT EXISTS interpretation_degree BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS country TEXT,
ADD COLUMN IF NOT EXISTS timezone TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS linkedin_profile TEXT,
ADD COLUMN IF NOT EXISTS website TEXT,
ADD COLUMN IF NOT EXISTS visibility TEXT DEFAULT 'public';
